user = User.create(username: "nathan", password: "12345")
survey1=user.surveys.create(title: "DBC Student Satisfaction Research",description: "This is a student satisfaction research conducted by ZIN research group. Your response will help DBC to improve the quality of the education it provides.")
question1=survey1.questions.create(content:"How likely are you to recommend DBC to a friend?")
question1.answers.create(content:"Very Likely")
question1.answers.create(content:"Likely")
question1.answers.create(content:"Maybe")
question1.answers.create(content:"Not Likely")
question1.answers.create(content:"No")
question2=survey1.questions.create(content:"How do you feel about the fact that this $14k program does not provide lunch?")
question2.answers.create(content:"I'm cool with it. Other bootcamps don't provide lunch either.")
question2.answers.create(content:"It doesn't matter to me.")
question2.answers.create(content:"I don't like it. DBC should definitely provide lunch.")
question2.answers.create(content:"Maybe DBC should connect with local restaurants and provide optional group discount for its students.")
question3=survey1.questions.create(content:"How do you like the keyboards provided at DBC?")
question3.answers.create(content:"Too tiny")
question3.answers.create(content:"Skips characters")
question3.answers.create(content:"Lacks wrist support")
question3.answers.create(content:"Lacks key springiness")
question3.answers.create(content:"All the above")
question4=survey1.questions.create(content:"What would be cool?")
question4.answers.create(content:"Shower facility")
question4.answers.create(content:"In-house gym")
question4.answers.create(content:"Larger lockers")
question4.answers.create(content:"Parking facility")
question4.answers.create(content:"Partnership with NJ Transit and MTA to provide student discount")

survey2=user.surveys.create(title: "MTA Transportation Research/Do Not Use",description: "This survey has the same content from the DBC campus research.")
question1=survey2.questions.create(content:"How likely are you to recommend DBC to a friend?")
question1.answers.create(content:"Very Likely")
question1.answers.create(content:"Likely")
question1.answers.create(content:"Maybe")
question1.answers.create(content:"Not Likely")
question1.answers.create(content:"No")
question2=survey2.questions.create(content:"How do you feel about the fact that this $14k program does not provide lunch?")
question2.answers.create(content:"I'm cool with it. Other bootcamps don't provide lunch either.")
question2.answers.create(content:"It doesn't matter to me.")
question2.answers.create(content:"I don't like it. DBC should definitely provide lunch.")
question2.answers.create(content:"Maybe DBC should connect with local restaurants and provide optional group discount for its students.")
question3=survey2.questions.create(content:"How do you like the keyboards provided at DBC?")
question3.answers.create(content:"Too tiny")
question3.answers.create(content:"Skips characters")
question3.answers.create(content:"Lacks wrist support")
question3.answers.create(content:"Lacks key springiness")
question3.answers.create(content:"All the above")
question4=survey2.questions.create(content:"What would be cool?")
question4.answers.create(content:"Shower facility")
question4.answers.create(content:"In-house gym")
question4.answers.create(content:"Larger lockers")
question4.answers.create(content:"Parking facility")
question4.answers.create(content:"Partnership with NJ Transit and MTA to provide student discount")
